### ISSUE TITLE
https://github.com/Geekhub-J4W/geekhub-j4w-13-AnnaHavryliuk4/commit/5f199d1f1bfb25d2db94cc4661559b60a1d7b4eb

### ISSUE THREAD

**Issue by AnnaHavryliuk4** [Geekhub-J4W/geekhub-j4w-13-AnnaHavryliuk4#1]

**Comment by V-Nikolenko** [comment]
Pipelines failed! Check your code for code smells and logic correctness

Your code won't compile until you merge the changes from the template repository. The quality pipeline failed due to the absence of important SonarQube configuration rules. Please import the template changes into your repository.
